export interface IrregularVerb {
  base: string;
  transcriptionBase: string;
  past: string;
  transcriptionPast: string;
  participle: string;
  transcriptionParticiple: string;
  translation: string;
}

export const irregularVerbs: IrregularVerb[] = [
  { base: 'be', transcriptionBase: '[би]', past: 'was/were', transcriptionPast: '[уо́з]/[уо́]', participle: 'been', transcriptionParticiple: '[бин]', translation: 'быть' },
  { base: 'become', transcriptionBase: '[бика́м]', past: 'became', transcriptionPast: '[бикэ́йм]', participle: 'become', transcriptionParticiple: '[бика́м]', translation: 'становиться' },
  { base: 'begin', transcriptionBase: '[биги́н]', past: 'began', transcriptionPast: '[бигэ́н]', participle: 'begun', transcriptionParticiple: '[бига́н]', translation: 'начинать' },
  { base: 'break', transcriptionBase: '[брэйк]', past: 'broke', transcriptionPast: '[броук]', participle: 'broken', transcriptionParticiple: '[бро́укэн]', translation: 'ломать' },
  { base: 'bring', transcriptionBase: '[бринг]', past: 'brought', transcriptionPast: '[брот]', participle: 'brought', transcriptionParticiple: '[брот]', translation: 'приносить' },
  { base: 'build', transcriptionBase: '[билд]', past: 'built', transcriptionPast: '[билт]', participle: 'built', transcriptionParticiple: '[билт]', translation: 'строить' },
  { base: 'buy', transcriptionBase: '[бай]', past: 'bought', transcriptionPast: '[бот]', participle: 'bought', transcriptionParticiple: '[бот]', translation: 'покупать' },
  { base: 'catch', transcriptionBase: '[кэч]', past: 'caught', transcriptionPast: '[кот]', participle: 'caught', transcriptionParticiple: '[кот]', translation: 'ловить' },
  { base: 'choose', transcriptionBase: '[чуз]', past: 'chose', transcriptionPast: '[чоуз]', participle: 'chosen', transcriptionParticiple: '[чо́узэн]', translation: 'выбирать' },
  { base: 'come', transcriptionBase: '[кам]', past: 'came', transcriptionPast: '[кэйм]', participle: 'come', transcriptionParticiple: '[кам]', translation: 'приходить' },
  { base: 'cost', transcriptionBase: '[кост]', past: 'cost', transcriptionPast: '[кост]', participle: 'cost', transcriptionParticiple: '[кост]', translation: 'стоить' },
  { base: 'cut', transcriptionBase: '[кот]', past: 'cut', transcriptionPast: '[кот]', participle: 'cut', transcriptionParticiple: '[кот]', translation: 'резать' },
  { base: 'do', transcriptionBase: '[ду]', past: 'did', transcriptionPast: '[дид]', participle: 'done', transcriptionParticiple: '[дан]', translation: 'делать' },
  { base: 'draw', transcriptionBase: '[дро]', past: 'drew', transcriptionPast: '[дру]', participle: 'drawn', transcriptionParticiple: '[дрон]', translation: 'рисовать' },
  { base: 'drink', transcriptionBase: '[дринк]', past: 'drank', transcriptionPast: '[дрэнк]', participle: 'drunk', transcriptionParticiple: '[дранк]', translation: 'пить' },
  { base: 'drive', transcriptionBase: '[драйв]', past: 'drove', transcriptionPast: '[дроув]', participle: 'driven', transcriptionParticiple: '[дри́вэн]', translation: 'водить (авто)' },
  { base: 'eat', transcriptionBase: '[ит]', past: 'ate', transcriptionPast: '[эйт]', participle: 'eaten', transcriptionParticiple: '[и́тн]', translation: 'есть' },
  { base: 'fall', transcriptionBase: '[фол]', past: 'fell', transcriptionPast: '[фэл]', participle: 'fallen', transcriptionParticiple: '[фо́лэн]', translation: 'падать' },
  { base: 'feel', transcriptionBase: '[фил]', past: 'felt', transcriptionPast: '[фэлт]', participle: 'felt', transcriptionParticiple: '[фэлт]', translation: 'чувствовать' },
  { base: 'find', transcriptionBase: '[файнд]', past: 'found', transcriptionPast: '[фаунд]', participle: 'found', transcriptionParticiple: '[фаунд]', translation: 'находить' },
  { base: 'fly', transcriptionBase: '[флай]', past: 'flew', transcriptionPast: '[флу]', participle: 'flown', transcriptionParticiple: '[флоун]', translation: 'летать' },
  { base: 'forget', transcriptionBase: '[фэгэ́т]', past: 'forgot', transcriptionPast: '[фэга́т]', participle: 'forgotten', transcriptionParticiple: '[фэга́тан]', translation: 'забывать' },
  { base: 'get', transcriptionBase: '[гэт]', past: 'got', transcriptionPast: '[гат]', participle: 'got/gotten', transcriptionParticiple: '[гат]/[га́тан]', translation: 'получать' },
  { base: 'give', transcriptionBase: '[гив]', past: 'gave', transcriptionPast: '[гэйв]', participle: 'given', transcriptionParticiple: '[ги́ван]', translation: 'давать' },
  { base: 'go', transcriptionBase: '[гоу]', past: 'went', transcriptionPast: '[уэ́нт]', participle: 'gone', transcriptionParticiple: '[гон]', translation: 'идти' },
  { base: 'grow', transcriptionBase: '[гроу]', past: 'grew', transcriptionPast: '[гру]', participle: 'grown', transcriptionParticiple: '[гроун]', translation: 'расти' },
  { base: 'have', transcriptionBase: '[хэв]', past: 'had', transcriptionPast: '[хёд]', participle: 'had', transcriptionParticiple: '[хёд]', translation: 'иметь' },
  { base: 'hear', transcriptionBase: '[хир]', past: 'heard', transcriptionPast: '[хёд]', participle: 'heard', transcriptionParticiple: '[хёд]', translation: 'слышать' },
  { base: 'hide', transcriptionBase: '[хайд]', past: 'hid', transcriptionPast: '[хид]', participle: 'hidden', transcriptionParticiple: '[хи́дн]', translation: 'прятать' },
  { base: 'hit', transcriptionBase: '[хит]', past: 'hit', transcriptionPast: '[хит]', participle: 'hit', transcriptionParticiple: '[хит]', translation: 'ударять' },
  { base: 'hold', transcriptionBase: '[хоулд]', past: 'held', transcriptionPast: '[хэлд]', participle: 'held', transcriptionParticiple: '[хэлд]', translation: 'держать' },
  { base: 'hurt', transcriptionBase: '[хёрт]', past: 'hurt', transcriptionPast: '[хёрт]', participle: 'hurt', transcriptionParticiple: '[хёрт]', translation: 'причинять боль' },
  { base: 'keep', transcriptionBase: '[кип]', past: 'kept', transcriptionPast: '[кэпт]', participle: 'kept', transcriptionParticiple: '[кэпт]', translation: 'хранить' },
  { base: 'know', transcriptionBase: '[ноу]', past: 'knew', transcriptionPast: '[нью]', participle: 'known', transcriptionParticiple: '[ноун]', translation: 'знать' },
  { base: 'leave', transcriptionBase: '[лив]', past: 'left', transcriptionPast: '[лефт]', participle: 'left', transcriptionParticiple: '[лефт]', translation: 'покидать' },
  { base: 'lend', transcriptionBase: '[ленд]', past: 'lent', transcriptionPast: '[лент]', participle: 'lent', transcriptionParticiple: '[лент]', translation: 'одалживать' },
  { base: 'let', transcriptionBase: '[лет]', past: 'let', transcriptionPast: '[лет]', participle: 'let', transcriptionParticiple: '[лет]', translation: 'позволять' },
  { base: 'lose', transcriptionBase: '[луз]', past: 'lost', transcriptionPast: '[лост]', participle: 'lost', transcriptionParticiple: '[лост]', translation: 'терять' },
  { base: 'make', transcriptionBase: '[мэйк]', past: 'made', transcriptionPast: '[мэйд]', participle: 'made', transcriptionParticiple: '[мэйд]', translation: 'делать' },
  { base: 'mean', transcriptionBase: '[мин]', past: 'meant', transcriptionPast: '[мэнт]', participle: 'meant', transcriptionParticiple: '[мэнт]', translation: 'значить' },
  { base: 'meet', transcriptionBase: '[мит]', past: 'met', transcriptionPast: '[мэт]', participle: 'met', transcriptionParticiple: '[мэт]', translation: 'встречать' },
  { base: 'pay', transcriptionBase: '[пэй]', past: 'paid', transcriptionPast: '[пэйд]', participle: 'paid', transcriptionParticiple: '[пэйд]', translation: 'платить' },
  { base: 'put', transcriptionBase: '[пут]', past: 'put', transcriptionPast: '[пут]', participle: 'put', transcriptionParticiple: '[пут]', translation: 'класть' },
  { base: 'read', transcriptionBase: '[рид]', past: 'read', transcriptionPast: '[рид]', participle: 'read', transcriptionParticiple: '[рид]', translation: 'читать' },
  { base: 'ride', transcriptionBase: '[райд]', past: 'rode', transcriptionPast: '[роуд]', participle: 'ridden', transcriptionParticiple: '[ри́дн]', translation: 'ездить верхом' },
  { base: 'ring', transcriptionBase: '[ринг]', past: 'rang', transcriptionPast: '[рэнг]', participle: 'rung', transcriptionParticiple: '[ранг]', translation: 'звонить' },
  { base: 'run', transcriptionBase: '[ран]', past: 'ran', transcriptionPast: '[рэн]', participle: 'run', transcriptionParticiple: '[ран]', translation: 'бежать' },
  { base: 'say', transcriptionBase: '[сэй]', past: 'said', transcriptionPast: '[сэд]', participle: 'said', transcriptionParticiple: '[сэд]', translation: 'говорить' },
  { base: 'see', transcriptionBase: '[си]', past: 'saw', transcriptionPast: '[со]', participle: 'seen', transcriptionParticiple: '[син]', translation: 'видеть' },
  { base: 'sell', transcriptionBase: '[сэл]', past: 'sold', transcriptionPast: '[соулд]', participle: 'sold', transcriptionParticiple: '[соулд]', translation: 'продавать' },
  { base: 'send', transcriptionBase: '[сэнд]', past: 'sent', transcriptionPast: '[сэнт]', participle: 'sent', transcriptionParticiple: '[сэнт]', translation: 'посылать' },
  { base: 'show', transcriptionBase: '[шоу]', past: 'showed', transcriptionPast: '[шоуд]', participle: 'shown', transcriptionParticiple: '[шоун]', translation: 'показывать' },
  { base: 'shut', transcriptionBase: '[шат]', past: 'shut', transcriptionPast: '[шат]', participle: 'shut', transcriptionParticiple: '[шат]', translation: 'закрывать' },
  { base: 'sing', transcriptionBase: '[синг]', past: 'sang', transcriptionPast: '[сэнг]', participle: 'sung', transcriptionParticiple: '[санг]', translation: 'петь' },
  { base: 'sit', transcriptionBase: '[сит]', past: 'sat', transcriptionPast: '[сэт]', participle: 'sat', transcriptionParticiple: '[сэт]', translation: 'сидеть' },
  { base: 'sleep', transcriptionBase: '[слип]', past: 'slept', transcriptionPast: '[слепт]', participle: 'slept', transcriptionParticiple: '[слепт]', translation: 'спать' },
  { base: 'speak', transcriptionBase: '[спик]', past: 'spoke', transcriptionPast: '[споук]', participle: 'spoken', transcriptionParticiple: '[спо́укэн]', translation: 'говорить' },
  { base: 'spend', transcriptionBase: '[спэнд]', past: 'spent', transcriptionPast: '[спэнт]', participle: 'spent', transcriptionParticiple: '[спэнт]', translation: 'тратить' },
  { base: 'stand', transcriptionBase: '[стэнд]', past: 'stood', transcriptionPast: '[студ]', participle: 'stood', transcriptionParticiple: '[студ]', translation: 'стоять' },
  { base: 'swim', transcriptionBase: '[суи́м]', past: 'swam', transcriptionPast: '[суэ́м]', participle: 'swum', transcriptionParticiple: '[суа́м]', translation: 'плавать' },
  { base: 'take', transcriptionBase: '[тэйк]', past: 'took', transcriptionPast: '[тук]', participle: 'taken', transcriptionParticiple: '[тэ́йкэн]', translation: 'брать' },
  { base: 'teach', transcriptionBase: '[тич]', past: 'taught', transcriptionPast: '[тот]', participle: 'taught', transcriptionParticiple: '[тот]', translation: 'учить' },
  { base: 'tell', transcriptionBase: '[тэл]', past: 'told', transcriptionPast: '[тоулд]', participle: 'told', transcriptionParticiple: '[тоулд]', translation: 'рассказывать' },
  { base: 'think', transcriptionBase: '[синк]', past: 'thought', transcriptionPast: '[сот]', participle: 'thought', transcriptionParticiple: '[сот]', translation: 'думать' },
  { base: 'throw', transcriptionBase: '[сроу]', past: 'threw', transcriptionPast: '[сру]', participle: 'thrown', transcriptionParticiple: '[сроун]', translation: 'бросать' },
  { base: 'understand', transcriptionBase: '[андэстэ́нд]', past: 'understood', transcriptionPast: '[андэсту́д]', participle: 'understood', transcriptionParticiple: '[андэсту́д]', translation: 'понимать' },
  { base: 'wake', transcriptionBase: '[уэ́йк]', past: 'woke', transcriptionPast: '[уо́ук]', participle: 'woken', transcriptionParticiple: '[уо́укэн]', translation: 'будить' },
  { base: 'wear', transcriptionBase: '[уэ́а]', past: 'wore', transcriptionPast: '[уо́р]', participle: 'worn', transcriptionParticiple: '[уо́рн]', translation: 'носить (одежду)' },
  { base: 'win', transcriptionBase: '[уи́н]', past: 'won', transcriptionPast: '[уа́н]', participle: 'won', transcriptionParticiple: '[уа́н]', translation: 'выигрывать' },
  { base: 'write', transcriptionBase: '[райт]', past: 'wrote', transcriptionPast: '[роут]', participle: 'written', transcriptionParticiple: '[ри́тн]', translation: 'писать' }
];